# FROM node:16
# WORKDIR /usr/app
# COPY package*.json .
# RUN npm install
# COPY . .

FROM node:16
WORKDIR /app
COPY package.json .
ARG NODE_ENV
RUN npm install
RUN apt update
RUN apt install vim -y
COPY . .
CMD ["npm", "start"]